branch-defaults:
  default:
    environment: udagram-api-2-dev
    group_suffix: null
deploy:
  arifact: www/Archive.zip
global:
  application_name: udagram-api-2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
